name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*.*.*-dev'
      - 'v*.*.*-test'
      - 'v*.*.*-stage'
      - 'v*.*.*-prod'

jobs:
  build:
    runs-on: ubuntu-latest  # Can be set to macos-latest if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Linting
      run: flake8 app/

    - name: Stop any running container on port 8000
      run: |
        existing_container=$(docker ps -q --filter "publish=8000")
        if [ -n "$existing_container" ]; then
          echo "Stopping container running on port 8000..."
          docker stop $existing_container
          docker rm $existing_container
        fi

    - name: Build Docker image
      run: docker build -t llm-inference-pipeline:${{ github.ref_name }} .

    - name: Run Docker container
      run: docker run -d --name llm_container -p 8000:8000 llm-inference-pipeline:${{ github.ref_name }}

    - name: Wait for the service to start
      run: sleep 100  # Adjust the sleep time as necessary to allow the service to start

    - name: Test API endpoint
      run: |
        curl -X POST "http://localhost:8000/infer" -H "Content-Type: application/json" -d '{"prompt": "Hello, LLM!"}'

    - name: Stop and remove Docker container
      run: |
        docker stop llm_container
        docker rm llm_container

    - name: Deploy to environment
      if: github.ref_name == 'v*.*.*-prod'
      run: echo "Deploying to production environment"

